version: '3'
services:
  service:
    build: ./app
    container_name: service
    volumes:
      - static_volume:/opt/app/static/
      - ./fixtures:/opt/app/fixtures
    env_file: ./.env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static
    depends_on:
      - service
    restart: always
    ports:
      - "80:80"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    volumes:
      - ./openapi.yaml:/swagger.yaml
    environment:
      - SWAGGER_JSON=/swagger.yaml
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  static_volume: